if(EXISTS "/Users/kab/Projects/Portfolio/cross_platform_signal/build-sensys-app/lib/survey_processor/test_survey_processor[1]_tests.cmake")
  include("/Users/kab/Projects/Portfolio/cross_platform_signal/build-sensys-app/lib/survey_processor/test_survey_processor[1]_tests.cmake")
else()
  add_test(test_survey_processor_NOT_BUILT test_survey_processor_NOT_BUILT)
endif()
