// Numeric parity tests: C++ FxLMS must match Python (MATLAB-equivalent) golden vectors.
// Golden vectors generated by tests/gen_golden.py with MU=0.01, N_W=8, N_SP=4, omega=0.15, N=32.
#include <gtest/gtest.h>
#include <array>
#include <cmath>
#include "anc/fxlms.hpp"
#include "anc/secondary_path.hpp"

using namespace anc;

// Golden vectors (generated by gen_golden.py)
constexpr std::array<float, 32> golden_ref = {{0.00000000f, 0.14943813f, 0.29552022f, 0.43496552f, 0.56464249f, 0.68163878f, 0.78332692f, 0.86742324f, 0.93203908f, 0.97572339f, 0.99749500f, 0.99686503f, 0.97384763f, 0.92895973f, 0.86320937f, 0.77807319f, 0.67546320f, 0.55768371f, 0.42737988f, 0.28747800f, 0.14112000f, -0.00840725f, -0.15774569f, -0.30354151f, -0.44252044f, -0.57156134f, -0.68776613f, -0.78852528f, -0.87157577f, -0.93505257f, -0.97753012f, -0.99805444f}};
constexpr std::array<float, 32> golden_output = {{0.00000000f, 0.00000000f, 0.00000000f, 0.00015367f, 0.00106136f, 0.00395932f, 0.01070593f, 0.02357259f, 0.04486541f, 0.07644475f, 0.11923432f, 0.17229992f, 0.23256555f, 0.29504243f, 0.35348010f, 0.40125990f, 0.43238619f, 0.44239154f, 0.42898539f, 0.39232802f, 0.33488292f, 0.26088405f, 0.17552763f, 0.08405236f, -0.00911007f, -0.10094706f, -0.19012350f, -0.27684247f, -0.36234558f, -0.44816378f, -0.53528172f, -0.62339568f}};
constexpr std::array<float, 8>  golden_weights_final = {{0.14856187f, 0.13798758f, 0.12480735f, 0.10952171f, 0.09266281f, 0.07477824f, 0.05641484f, 0.03810332f}};

// Secondary path matching make_default_secondary_path()
static SecondaryPath<4> parity_sp() {
    return SecondaryPath<4>({0.0f, 0.8f, 0.15f, 0.05f});
}

// C++ FxLMS output for each sample must match Python golden within 1e-4.
TEST(Parity, FxLMSOutputMatchesGolden) {
    auto sp = parity_sp();
    FxLMS<8, 4> fxlms(0.01f, 0.0f, sp);

    for (std::size_t n = 0; n < 32; ++n) {
        float ref = golden_ref[n];
        float y   = fxlms.process(ref, ref);  // error = ref
        EXPECT_NEAR(y, golden_output[n], 1e-4f) << "mismatch at n=" << n;
    }
}

// Final C++ weights must match Python golden within 1e-4.
TEST(Parity, FxLMSFinalWeightsMatchGolden) {
    auto sp = parity_sp();
    FxLMS<8, 4> fxlms(0.01f, 0.0f, sp);

    for (std::size_t n = 0; n < 32; ++n)
        fxlms.process(golden_ref[n], golden_ref[n]);

    const auto& w = fxlms.weights();
    for (std::size_t i = 0; i < 8; ++i)
        EXPECT_NEAR(w[i], golden_weights_final[i], 1e-4f) << "weight mismatch at i=" << i;
}

// Secondary-path convolution parity: C++ FIR output must match reference computation.
TEST(Parity, SecondaryPathConvolution) {
    // Python reference: y[n] = sum(h[k] * x[n-k]) with h = {0,0.8,0.15,0.05}
    // y[n] = 0*x[n] + 0.8*x[n-1] + 0.15*x[n-2] + 0.05*x[n-3]
    const std::array<float, 8> x_in = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f};
    const std::array<float, 8> expected = {0.0f, 0.8f, 1.75f, 2.75f, 3.75f, 4.75f, 5.75f, 6.75f};

    auto sp = parity_sp();
    for (std::size_t n = 0; n < 8; ++n)
        EXPECT_NEAR(sp.apply(x_in[n]), expected[n], 1e-5f) << "SP mismatch at n=" << n;
}
